const { Types } = require("../api/common/constants");

const Adventure = [
  "Abseil Down a Waterfall",
  "Air Boat Across an Alligator Infested Swamp",
  "Arrive By Seaplane",
  "Catch a Wave Surfing",
  "Dog Sled",
  "Ride a Zip Line",
  "Eat Fire",
  "Explore a Cave",
  "Flip on a Trampoline",
  "Go Flyboarding",
  "Get a Tattoo",
  "Go Bamboo Rafting",
  "Go Fat Biking",
  "Hang Glide",
  "Hold a Shark",
  "Indoor Skydive",
  "Jump Off a Cliff",
  "Kite Surf",
  "Navigate a Personal Underwater SUB",
  "Parasail",
  "Play a Game of Paintball",
  "Police Ride Along",
  "Rappel Down a Waterfall",
  "Rappel into a Cave",
  "Ride ATVs",
  "Ride in a Hot Air Balloon",
  "Ride in a Luge",
  "Sail a Boat",
  "Scuba Dive",
  "Go Skijoring",
  "Go Skydive",
  "Go Snowboard",
  "Swim with Dolphins",
  "Swim with Sharks",
  "Swim with Stingrays",
  "Walk a Suspension Bridge",
  "Walk on Hot Coals",
  "Go Whitewater Rafting",
  "Wrap a Snake Around [TARGET] Neck",
  "Go Zorbing",
];

const Nature = [
  "Attend a Rodeo",
  "Bathe an Elephant",
  "Chase a Tornado",
  "Go Clamming",
  "Climb a Volcano",
  "Climb to the Top of a Tree",
  "Compete in a Frog Jumping Contest",
  "Complete a Horse Jumping Obstacle",
  "Drive Through a Dust Storm",
  "Feed a Crocodile",
  "Feed a Koala Bear",
  "Feed an Ostrich",
  "Herd Cattle",
  "Hike Every Trail at a State Park",
  "Hold a Monkey",
  "Hold a Tarantula Size Spider",
  "Horseback Ride on the Beach",
  "Hug a Redwood",
  "Kiss a Sea Lion",
  "Kiss in the Rain",
  "Make a Snowman",
  "Milk a Cow",
  "Name a Star",
  "Relax in a Natural Hot Spring",
  "Release Baby Turtles into the Ocean",
  "Ride a Horse Bareback",
  "Ride in a Horse & Carriage",
  "Roll in a Huge Pile of Leaves",
  "See a Coral Reef",
  "See the Salmon Run",
  "Shear a Sheep",
  "Go Shrimping",
  "Sleep in a Stable on a Haystack",
  "Sleep in a Yurt",
  "Sleep in an Igloo",
  "Stand Under a Waterfall",
  "Swim in the Ocean",
  "Swim in an Aquarium",
  "Swim with a School of Fish",
  "Swim with Manatees",
  "Swim with Sea Turtles",
  "Take a Falconry Class",
  "Walk on a Black Sand Beach",
  "Watch a Caterpillar Turn into a Butterfly",
  "Watch the Sunrise & Sunset in one Day",
  "Witness a Solar Eclipse",
  "Go Whale Watching",
];

const People = [
  "Answer a Personal Ad",
  "Attend a High School Reunion",
  "Be a Groomsman",
  "Be a Best Man",
  "Be Considered a Dilf",
  "Celebrate a Same Sex Wedding",
  "Cover the Bed in Rose Petals",
  "Find [TARGET] Best Friend from High School",
  "Find Your First Love",
  "Forgive Someone",
  "Get Engaged",
  "Get Married",
  "Go on a Blind Date",
  "Go on a Double Date",
  "Have a Meaningful Conversation With a Stranger",
  "Host a Family Reunion",
  "Kiss a Stranger",
  "Kiss on Top of a Ferris Wheel",
  "Make a New Friend",
  "Meet a Blog Reader in Person",
  "Meet a World Leader",
  "Meet Someone Famous",
  "Meet the President",
  "Organize a Family Portrait",
  "Plan a Date Night with [TARGET] Spouse",
  "Play Matchmaker",
  "Receive a Fan Letter",
  "Reconnect with an Old Friend",
  "Share a Cab with a Stranger",
  "Sing a Karaoke Duet",
  "Spend Time with a Person From Another Generation",
  "Stay up all Night Talking",
  "Surprise Someone",
  "Tell Dad I Love Him",
  "Visit your Childhood Home",
  "Write a Love Note with Lipstick on the Bathroom Mirror",
  "Write a Thank you Letter to a Company that Treated you well",
];

const Creative = [
  "Act in a Play",
  "Be Published",
  "Blow Glass",
  "Complete a Cross Stitch Piece",
  "Complete a “Paint by Numbers” piece of art",
  "Create a Bumper Sticker",
  "Create a Family Logo",
  "Create a Family Tree",
  "Create a Flower Arrangement",
  "Create a Piece of Art & Sell it",
  "Create your own Personal Stationary",
  "Decorate a Blank T-Shirt",
  "Decoupage Something",
  "Design a Website",
  "Enter Art in an Exhibit",
  "Get Your Handwriting Analyzed",
  "Have your Nude Body Artistically Painted",
  "Knit a Scarf",
  "Make a Calendar with [TARGET] own Photos",
  "Make a Candle",
  "Make a Coloring Book",
  "Make a Font Out of [TARGET] Handwriting",
  "Make a Handmade Gift",
  "Make a Handmade Greeting Card",
  "Make a Scrapbook",
  "Make a Tie Dye Shirt",
  "Make an Origami Animal",
  "Make Mosaic Art",
  "Make Paper",
  "Make Soap",
  "Make Stained Glass",
  "Paint Something at a Ceramic Store",
  "Refinish a Piece of Furniture",
  "Sew Something you can Wear",
  "Start a Blog",
  "Take a Painting Class",
  "Take an Art Class",
  "Take Pictures in a Photo Booth",
  "Work on a Pottery Wheel",
  "Wrap a Present Perfectly",
  "Write a Letter in Calligraphy",
  "Write a Song",
];

const Entertainment = [
  "Act in a Play",
  "Apply to be on a Reality Show",
  "Attend a Black Tie Gala",
  "Attend a Boxing Match",
  "Attend a Film Premiere",
  "Attend a Foam Party",
  "Attend a Gallery Opening",
  "Attend a Gay Pride Event",
  "Attend a Jazz Festival",
  "Attend a Masquerade",
  "Attend a Murder Mystery Dinner",
  "Attend a Music Festival",
  "Attend a Native American Pow Wow",
  "Attend a Poetry Reading",
  "Attend a Wedding in a Different Country",
  "Attend a White Party",
  "Attend a WWE Match",
  "Be a Game Show Contestant",
  "Be a Member of a TV Studio Audience",
  "Be an Extra in a Movie",
  "Be in a Commercial",
  "Be on a Radio Show",
  "Be on a TV Show",
  "Be on the Cover of a Magazine",
  "Be a Street Performer",
  "Bet at the Dog Races",
  "Bicycle Across the Golden Gate",
  "Buy the Best Seat in the House",
  "Close the Club",
  "Contact Someone with [TARGET] Own Name",
  "Create a Video & Upload it to the Internet",
  "Crowd Surf",
  "Dance at a Rave",
  "Dance on a Bar",
  "Dance With Ellen Degeneres",
  "Design a Room I Love",
  "Do a Body Shot",
  "Do the Hula",
  "Fly on a Trapeze",
  "Get a Caricature Drawing by a Street Artist",
  "Get Comped/Upgraded Something",
  "Get Hypnotized",
  "Get Swag",
  "Get VIP Passes to a Show",
  "Go on a Cruise",
  "Go to a Blues Bar",
  "Go to a Book Signing",
  "Go to a Miniature Museum",
  "Go to a Roller Derby",
  "Go to a Toga Party",
  "Go to Dinner Theater",
  "Go to a Drive-In Movie",
  "Go to a Rave",
  "Go to an Indycar Race",
  "Go to Nascar",
  "Go to a Paint Party",
  "Go to a Renaissance Festival",
  "Go to a Tattoo Festival",
  "Go to Comicon",
  "Go to the Movies by [TARGET_OWNED]",
  "Have 15 Minutes of Fame",
  "Be in the Newspaper",
  "Host a Game Night",
  "Host a Radio Show",
  "Join a Flash Mob",
  "Learn a Line Dance",
  "Learn How to Sing Within [TARGET] Octave",
  "Make a Great Toast",
  "Make a House of Cards",
  "Master a Video Game",
  "Meet Oprah",
  "Party in a Private Booth at a Nightclub",
  "Perform a Magic Trick",
  "Play a Pinball Machine",
  "Play a Song on a Harmonica",
  "Play Bingo at a Bingo Hall",
  "Pose with a Figure at a Wax Museum",
  "Read the Book Before the Movie",
  "Receive a Fan Letter",
  "Record a Song",
  "Ride a Mechanical Bull",
  "Ride on a Ferris Wheel",
  "See a 3-D movie",
  "See a Ballet",
  "See a Broadway Play",
  "See a Cirque du Soleil Show",
  "See a Foreign Film",
  "See a Las Vegas Show",
  "See a TED Talk Live",
  "See the Tour de France",
  "See a Wimbledon Match Live",
  "See an Opera",
  "See [TARGET] Favorite Band Play Live",
  "Set a Guinness Book of World Record",
  "Sing Karaoke in Public",
  "Sit Front Row at a Basketball Game",
  "Take a Burlesque Class",
  "Take a New Route to Work",
  "Take an Improv Class",
  "Throw a Themed Party",
  "Throw Beads at Mardi Gras",
  "Touch a Famous Piece of Art",
  "Walk the Red Carpet",
  "Watch a Documentary",
  "Watch all the Oscar Winning Best Pictures",
  "Watch all the Golden Globe Winning Best Pictures",
  "Watch the Space Shuttle Launch",
  "Wear a Sumo Wrestling Suit",
  "Yodel",
];

const Chef = [
  "Attend a Beer Festival",
  "Attend a Low Country Boil",
  "Attend a Pig Roast",
  "Attend a Tea Tasting",
  "Attend a Winemakers Dinner",
  "Bake a Cake for Someone Special",
  "Bake a Loaf of Bread",
  "Boil a Lobster",
  "Bottle a Recipe & Sell it",
  "Catch, Cook & Eat a Fish",
  "Cook a Traditional Dish from a Different Culture",
  "Cook Christmas Dinner",
  "Create an Ice Sculpture",
  "Cook Every Dish in One Cookbook",
  "Cook With a Celebrity Chef",
  "Cook With [TARGET] Partner",
  "Create a New Ice Cream Flavor",
  "Create Food Art",
  "Create Latte Art",
  "Create [TARGET] Own Cocktail",
  "Create [TARGET] Own Recipe",
  "Create [TARGET] Signature Dish",
  "Dismember a Chicken",
  "Drink a Bottle of Expensive Champagne",
  "Drink Absinthe",
  "Drink at a Distillery",
  "Drink at a Dive Bar",
  "Drink at an Ice Bar",
  "Drink Juice from a Fresh Coconut",
  "Drink Fresh Milk from the Cow",
  "Drink Moonshine",
  "Drink Sake",
  "Drink Tea at a Tea House",
  "Eat Breakfast in Bed",
  "Eat Ethiopian Food With [TARGET] Hand",
  "Eat a Meal Cooked by a Celebrity Chef",
  "Eat a Molecular Gastronomy Dinner",
  "Eat a Raw Diet for a Day",
  "Eat Alone at a Restaurant",
  "Eat an Insect",
  "Eat at a Michelin 3-star Restaurant",
  "Eat at a Food Truck",
  "Eat at the French Laundry",
  "Eat Caviar",
  "Eat in a Pitch Black Restaurant",
  "Eat Fondue",
  "Eat Southern BBQ in the South",
  "Enter Something in a Food Competition",
  "Extract Honey from a Bee Hive",
  "Fillet a Fish",
  "Go Oyster Hunting",
  "Go to a Vodka Lounge",
  "Go Wine Tasting",
  "Have a Dinner Party",
  "Have a Progressive Dining Experience",
  "Have a Wine Collection",
  "Host a Cookie Exchange",
  "Hunt for Wild Mushrooms",
  "Learn a Flair Bartending Trick",
  "Learn to Use Chopsticks",
  "Leave a 100% Tip for a Server",
  "Make a Gingerbread House",
  "Make Cheese",
  "Make Fresh Pasta",
  "Make Ice Cream",
  "Make Jam",
  "Make Sushi",
  "Make Wine",
  "Order One of Everything on a Menu",
  "Own a Food Cart",
  "Own an Award Winning Restaurant",
  "Partake in a Food Fight",
  "Partake in Afternoon Tea",
  "Participate in a Private Wine Tasting",
  "Pick Fruit From the Tree & Make a Pie",
  "Recreate a Childhood Recipe",
  "Recreate a Classic Dish",
  "Shuck Oysters",
  "Start an Herb Garden",
  "Stomp Grapes",
  "Take a Cooking Class",
  "Toss Pizza Dough in the Air",
  "Try Deep-Fried Twinkies",
  "Wade in a Cranberry Bog",
  "Write a Cookbook",
];

const Food = [
  "Try Ahi Poke",
  "Try Alligator",
  "Try Alpaca",
  "Try Ants",
  "Try Baby Eel",
  "Try Balut (Fertilized Egg)",
  "Try Beef Tongue",
  "Try Blood Sausage",
  "Try Bird Nest Soup",
  "Try Bone Marrow",
  "Try Cactus",
  "Try Casu Marzu",
  "Try Caviar",
  "Try Century Egg",
  "Try Cheeks",
  "Try Chicken Feet",
  "Try Conch",
  "Try Crickets",
  "Try Dim Sum",
  "Try Durian",
  "Try Eel",
  "Try Elk",
  "Try Escargot",
  "Try Flowers",
  "Try Foie Gras",
  "Try Frickles",
  "Try Frog Legs",
  "Try Fugu",
  "Try Gizzards",
  "Try Green Tuna Fruit",
  "Try Guinea Pig",
  "Try Haggis",
  "Try Head Cheese",
  "Try Heart",
  "Try Herring",
  "Try Jelly Fish",
  "Try Kimchi",
  "Try Lamb Tongue",
  "Try Lambs Brain",
  "Try Lambs Rump",
  "Try Liver",
  "Try Mealworm",
  "Try Mochi",
  "Try Mushy Peas",
  "Try Octopus",
  "Try Ostrich",
  "Try Pigeon",
  "Try Pigs Ear",
  "Try Pigs Feet",
  "Try Pigs Head",
  "Try Pigs Tail",
  "Try Pig Trotters (Feet)",
  "Try Rabbit",
  "Try Raw Oysters",
  "Try Reindeer",
  "Try Rocky Mountain Oysters",
  "Try Scrapple",
  "Try Sea Urchin",
  "Try Sashimi",
  "Try Scorpion",
  "Try Sea Slug",
  "Try Snake",
  "Try Sushi",
  "Try Tarantula",
  "Try Tequila Worm",
  "Try Tripe",
  "Try Truffle",
  "Try Ugli Fruit",
  "Try Wild Boar",
  "Try Worm Cakes",
  "Try Yak",
];

const Fun = [
  "Be Asked for [TARGET] Autograph",
  "Destroy Stuff in a Break Room",
  "Be on a Jumbotron at a Stadium",
  "Be on the New York Times Bestsellers List",
  "Bet on a Horse Race",
  "Build a House of Cards",
  "Build a Sand Castle",
  "Chop Firewood",
  "Coin a Word",
  "Complete a 1000-Piece Jigsaw Puzzle",
  "Do a Boudoir Photo Shoot",
  "Do a Wheelie on a Bike",
  "Do the Polar Bear Plunge",
  "Drive on the Other Side of the Road",
  "Eliminate Junk Mail",
  "Experience Weightlessness",
  "Experience Amish Country",
  "Find a Four Leaf Clover",
  "Find a Treasure With a Metal Detector",
  "Finish a Crossword Puzzle",
  "Find a Pearl in an Oyster",
  "Get a DNA Test",
  "Get a Standing Ovation",
  "Get a Tattoo",
  "Get Ordained",
  "Go Canoeing",
  "Google Search [TARGET] Name & Have at Least 1 Page of Stuff",
  "Haggle at an Open Market",
  "Have a Collection",
  "Have a Stranger Buy a Drink for You",
  "Have a White Christmas",
  "Invent Something",
  "Investigate an Urban Legend",
  "Join a Book Club",
  "Jump Into a Pool Fully Clothed",
  "Learn how to Pick a Lock",
  "Learn to Juggle",
  "Learn to Play Chess",
  "Learn Military Time",
  "Leave [TARGET] Mark in Graffiti",
  "Make a Balloon Animal",
  "Make a Model Car",
  "New Years Eve Kiss",
  "Own an Original Piece of Artwork",
  "Photobomb Someone",
  "Play a Game of Dominos",
  "Play a Game of Twister",
  "Play on a Slip-n-Slide",
  "Race an RC Car",
  "Read a Book on the NY Best Sellers List",
  "Recreate a Childhood Picture",
  "Research the Origins of your Surname",
  "Ride on one of the Largest Roller Coasters",
  "Rope Swing Into Water",
  "Run Through Sprinklers",
  "Saber a Champagne Bottle",
  "Send a Message in a Bottle",
  "Share Your Most Embarrassing Moment",
  "Slide Down a Firehouse Pole",
  "Skinny Dip",
  "Smoke a Fine Cigar",
  "Smoke a Hookah",
  "Solve a Rubiks Cube",
  "Start a Blog",
  "Start Fire Without Matches",
  "Stay Awake for 24 Hours",
  "Surprise Someone",
  "Take an Underwater Selfie",
  "Use a Chainsaw",
  "Use a Paddle to Bid at an Auction",
  "Walk on a Nude Beach Naked",
  "Walk on Stilts",
  "Whistle with a Blade of Grass",
  "Whistle with Two Fingers",
  "Win a Game of Monopoly",
  "Win a Stuffed Animal at a Carnival",
  "Win an Award",
  "Win Something",
  "Write Your Name in Wet Cement",
];

const Growth = [
  "Ask [TARGET] Spouse 20 Questions",
  "Attend a Random Free Seminar",
  "Be a Guest Speaker",
  "Be a Mentor",
  "Be an Organ Donor on [TARGET] License",
  "Be Present at a Birth",
  "Build a House With Habitat for Humanity",
  "Do 100 Hours of Volunteer Work",
  "Do 24-Hours of Silence",
  "Do a Charity Walk",
  "Do a Random Act of Kindness",
  "Donate 100,000 Grains of Rice to Help End World Hunger",
  "Donate Books",
  "Donate Clothing",
  "Donate Toys at the Holidays",
  "Entertain the Elderly at a Nursing Home",
  "Experience a New Religion",
  "Feed a Homeless Person",
  "Find the Meaning of Your Name",
  "Foster a Puppy",
  "Get a College Degree",
  "Give a Keynote Speech",
  "Give a Ted Talk",
  "Give Blood",
  "Give Someone a Hug",
  "Give Up Your Seat to Someone",
  "Help an Endangered/Injured Animal",
  "Help Someone Who is Lost",
  "Help Someone With a Check on Their Bucket List",
  "Learn a New Software Program",
  "Learn Conversational Spanish",
  "Learn CPR",
  "Learn the Alphabet in Sign Language",
  "Learn the Heimlich Maneuver",
  "Learn to Play a Song on an Instrument",
  "Learn to Say “Hello” in 10 Languages",
  "List 10 Things I am Grateful For Each Day",
  "Make a Kiva.com Loan",
  "Make a Significant Change in Someones Life",
  "Master a New Language",
  "Meditate",
  "Meet the Dalai Lama",
  "Participate in a Sweat Lodge Purification Ceremony",
  "Pay the Bridge Toll for the Person Behind Me",
  "Plant a Tree",
  "Put Change into Someones Expired Meter",
  "Read a Banned Book",
  "Read a Classic Novel",
  "Read a Story to a Child",
  "Read a Trilogy",
  "Rescue an Animaal",
  "Say “Thank You” in 10 Languages",
  "Send a Care Package to a Soldier",
  "Serve Food at a Soup Kitchen",
  "Send Flowers to Myself",
  "Spend a Day Helping at a Children’s Hospital",
  "Spend the Entire Day By Myself",
  "Spend a Week at a Silent Retreat",
  "Sponsor a Child’s Wish through the Make-a-Wish Foundation",
  "Start a Charity",
  "Teach a Class",
  "Unplug for a Week",
  "Vote in an Election",
  "Volunteer at a Dog Shelter",
  "Volunteer at an Orphanage",
  "Write a Book",
  "Write a Children’s Book",
  "Write a Letter to [TARGET] Future Self",
  "Write a Love Letter",
  "Write a Poem",
  "Write a Haiku",
];

const Health = [
  "Achieve [TARGET] Ideal Weight",
  "Attend a Professional Golf Tournament",
  "Attend the Olympics",
  "Barefoot Waterski",
  "Bet on the Winning Horse",
  "Bowl a Strike",
  "Bowl a Turkey (3 Strikes in a Row)",
  "Climb an Indoor Rock Wall",
  "Complete a Ropes Course",
  "Dive Off the High Diving Board",
  "Do a Belly Dance",
  "Do a Color Run",
  "Do a Handstand",
  "Do a Themed Run",
  "Drink only Water for a Week",
  "Finish a 10k",
  "Finish a Half Marathon",
  "Finish a Marathon",
  "Fly a Kite",
  "Go Ice Fishing",
  "Go Deep Sea Fishing",
  "Go Flyfishing",
  "Go Heli-Skiing",
  "Go Snowshoeing",
  "Go to a World Series Game",
  "Go to a Yoga Retreat",
  "Go to Nascar",
  "Go to the Super Bowl",
  "Golf 18 Holes",
  "Hit the Archery Bulls-Eye",
  "Join a Bowling League",
  "Jump at a Trampoline House",
  "Kayak",
  "Karate Chop & Break a Wood Board",
  "Learn to Curl",
  "Learn to Ice Skate Backwards",
  "Learn to Fence",
  "Learn to Surf",
  "Learn to Throw a Boomerang",
  "Make a Free Throw Shot",
  "Make a Hole in One",
  "Mud Wrestle",
  "Participate in a 5k Race",
  "Perfect a Karate Kick",
  "Play a Game of Pool Bowling",
  "Play a Round of Golf",
  "Play a Tennis Match",
  "Play Badminton",
  "Play Racquetball",
  "Ride Bikes on the Beach",
  "Rollerblade",
  "Run a 5k",
  "Run an 9 Minute Mile",
  "Scuba Dive",
  "Shoot a Machine Gun",
  "Skateboard on a Ramp",
  "Skeet Shoot",
  "Ski a Black Diamond Trail",
  "Snorkel",
  "Spar With a Professional Boxer",
  "Spin a Basketball on [TARGET] Finger",
  "Stand Up Paddle Board",
  "Survive at Paintball",
  "Swim in the Ocean",
  "Take a Pole Dancing Class",
  "Take a Self Defense Class",
  "Take a SoulCycle Class",
  "Take a Yoga Class",
  "Take a Zumba Class",
  "Tap Dance",
  "Throw an Axe",
  "Throw Out the First Pitch at a Major League Baseball Game",
  "Try Bikram Yoga",
  "Win a Game of 8-Ball",
  "Win a Game of Ping Pong",
];

const Transportation = [
  "Cruise in a Classic Car",
  "Cruise in a Low Rider",
  "Cruise on a Clipper Ship",
  "Drive a Race Car",
  "Drive a Snowmobile",
  "Drive a Speed Boat",
  "Drive a Tractor",
  "Drive a Zamboni",
  "Drive an ATV",
  "Fly in a Blimp",
  "Fly Emirates",
  "Fly in a Helicopter",
  "Fly in a Private Jet",
  "Go in a Submarine",
  "Go Off-Roading",
  "Play a Game of Croquet",
  "Race a Go Kart",
  "Ride a Camel",
  "Ride a Longboard",
  "Ride in a Cyclo",
  "Ride in a Glass Elevator",
  "Ride a Jetski",
  "Ride a Segway",
  "Ride a Unicycle",
  "Ride an Electric Bike",
  "Ride in a Dune Buggy",
  "Ride in a Gondola",
  "Ride in a Limousine",
  "Ride in a Songthaew",
  "Ride in a Tuk Tuk",
  "Ride on a Cable Car",
  "Ride on a Scary Roller Coaster",
  "Ride on a Subway",
  "Ride on a Tandem Bike",
  "Ride on a Train",
  "Test Drive a Sleek Sportscar",
  "Toboggan",
  "Tube Down a River",
];

const Global = [
  "Attend a Luau",
  "Attend a Unique Small-Town Festival",
  "Be a Tourist in You Own Town",
  "Celebrate a Holiday in a Different Country",
  "Climb to the Top of a Lighthouse",
  "Explore a Rain Forest",
  "Fly First Class",
  "Go on a Cruise",
  "Go on a Safari",
  "Go on a Spontaneous Road Trip",
  "Go to an Aquarium",
  "Pan for Gold",
  "Participate in a Japanese Tea Ceremony",
  "See a Blowhole",
  "See a Spectacular Fountain",
  "Sleep in a Capsule Hotel",
  "Sleep in a Haunted House",
  "Sleep in a Hostel",
  "Sleep on a Houseboat",
  "Sleep in a Teepee",
  "Sleep in a Treehouse",
  "Sleep in an Ice Hotel",
  "Sleep in an Overnight Train",
  "Stay at a Bed & Breakfast",
  "Stay at a Dude Ranch",
  "Stay in an Underwater Hotel",
  "Step Foot in all 7 Continents",
  "Take a Train Cross Country",
  "Take a trip with Mom",
  "Throw a Dart at a Map and Just Go",
  "Touch a Pyramid",
  "Tour a Factory",
  "Tour a Mayan Ruin",
  "Tour a Mission",
  "Tour a Vineyard",
  "Tour a Working Farm",
  "Travel Internationally",
  "Vacation Solo",
  "Vacation with a Stranger",
  "Visit 100 UNESCO World Heritage Sites",
  "Visit a Butterfly Sanctuary",
  "Visit a Castle",
  "Visit a Ghost Town",
  "Visit a Temple",
  "Visit a Tourist Attraction in [TARGET] Town",
  "Visit All 50 States",
  "Visit [TARGET] State Capitol",
  "Walk on a Glacier",
  "Wear a Fresh Lei",
];

const Travel = [
  "Ride the Orient Express",
  "Ride the Trans-Siberian Railway",
  "See the Beach Art by Andres Amador",
  "See the Northern Lights",
  "Shop at the European Christmas Markets",
  "Time Travel to Experience New Year’s Eve Twice",
  "Visit the Amazon",
  "Swim with Pink Dolphins – Amazon",
  "Step Foot on Antarctica",
  "See an Opera at the Sydney Opera House – Australia",
  "See the Red Crab Migration in Christmas Island – Austalia",
  "Snorkel the Great Barrier Reef – Australia",
  "Feed the Swimning Pigs in Exuma – Bahamas",
  "Swim in Dean’s Blue Hole – Bahamas",
  "Walk on the Pink Sand Beach – Bahamas",
  "Walk on the Salar de Uyuni Salt Flat – Bolivia",
  "Sleep in an Overwater Bungalow – Bora Bora",
  "Explore Angkor Wat – Cambodia",
  "Swim in the World’s Largest Pool – Chile",
  "Tour Patagonia – Chile/Argentina",
  "Take the Walk of Faith, Tianmen Mountain – China",
  "See the Hanging Temple in Mount Hengshan – China",
  "Walk the Great Wall of China – China",
  "Marvel at Plitvice Lakes – Croatia",
  "Walk the Nyhavn Waterfront in Copenhagen – Denmark",
  "Explore the Galapagos Islands – Ecuador",
  "Swing at the “End of the World” – Ecuador",
  "See the Pyramids of Giza – Egypt",
  "Walk Across Abbey Road in London – England",
  "Watch the Changing of the Guard at Buckingham Palace – England",
  "Backpack through Europe – Europe",
  "Stay in a Glass Igloo – Finland",
  "Attend Mass at Notre Dame Cathedral in Paris – France",
  "Put a Love Lock on Pont des Arts Bridge – France",
  "See the Eiffel Tower Glitter at Night – France",
  "See the Mona Lisa at the Louvre – France",
  "Sunbathe Topless on the French Riviera – France",
  "Visit the Palace of Versailles in France",
  "Walk Through the Lavender Fields in Provence – France",
  "Attend the Windjammer Parade – Germany",
  "Drink Beer at Oktoberfest – Germany",
  "Drink Kölsch Beer in Cologne – Germany",
  "Explore the Acropolis – Greece",
  "Watch the Sunset in Santorini – Greece",
  "Marvel at Kaieteur Falls – Guyana",
  "Hike the Active Pacaya Volcano – Guatemala",
  "Stroll through Antigua – Guatemala",
  "Tour a Windmill – Holland",
  "Climb to Tin Tian, Big Buddha – Hong Kong",
  "Soak in the Blue Lagoon – Iceland",
  "Get a Henna Tattoo – India",
  "Participate in the Rickshaw Run – India",
  "Stand in Front of the Taj Mahal – India",
  "Komodo National Park – Indonesia",
  "Walk through a Rice Terrace – Indonesia",
  "Drink at the Guinness Brewery – Ireland",
  "Kiss the Blarney Stone – Ireland",
  "Sleep in an Irish Castle – Ireland",
  "Visit the Holy Land in Jerusalem – Israel",
  "Attend the Palio Horse Race in Siena – Italy",
  "Explore the Coliseum in Rome – Italy",
  "Hear Andrea Bocelli sing opera in Milan – Italy",
  "Hear the Pope Speak at the Vatican – Italy",
  "Hike the Cities of Cinque Terre – Italy",
  "Learn to Make Pasta From Scratch – Italy",
  "Make a Wish in the Trevi Fountain – Italy",
  "Pose With the Leaning Tower of Pisa – Italy",
  "Ride a Vespa in Tuscany – Italy",
  "Ride in a Gondola in Venice – Italy",
  "Sleep in a Tuscan Villa – Italy",
  "Swim in the Blue Grotto – Italy",
  "Walk Across the Tibetan Bridge in Claviere – Italy",
  "Climb Mount Fuji – Japan",
  "See the Robot Restaurant Show – Japan",
  "See a Sumo Wrestling Practice at a Sumo Stable – Japan",
  "Stroll Through Sagano Bamboo Forest – Japan",
  "Tour the Japanese Gardens in Kyoto – Japan",
  "Visit the Jigokudani Monkey Park – Japan",
  "Walk Through the Wisteria Tunnel at Kawachi Fuji Gardens, in Kitakyushu – Japan",
  "Explore the Ancient Ruins of Petra – Jordan",
  "Float in the Dead Sea – Jordan/Israel",
  "Ride a Camel in the Wadi Rum Desert – Jordan",
  "Float Down Mekong River – Laos",
  "Explore Tam Ting Caves – Laos",
  "Mulu National Park – Malaysia",
  "Stay at the Boat Hotel in Cocoa Island – Maldives",
  "Eat in the Underwater Hotel – Maldives",
  "Swim in a Cenote – Mexico",
  "Swim with Whale Sharks – Mexico",
  "Snorkel the Underwater Museum – Mexico",
  "Gamble at Casino Monte Carlo – Monaco",
  "Explore the Van Gogh Museum – Netherlands",
  "See the Kinderdijk Windmills – Netherlands",
  "Explore the Waitomo Glowworm Cave – New Zealand",
  "Get Warm Near the Champagne Pool – New Zealand",
  "Go Black Water Rafting – New Zealand",
  "Hike the Franz Josef Glacier – New Zealand",
  "Board Down a Volcano – Nicaragua",
  "Sit on the Edge of Preikestolen – Norway",
  "Explore the Rock Islands Southern Lagoon – Palau",
  "Swim in Jellyfish Lake – Palau",
  "Hike the Inca Trail – Peru",
  "Hike Through the Crooked Forest – Poland",
  "Drink Port in Porto – Portugal",
  "See the Sky Gardens – Singapore",
  "See Gaudi’s La Sagrada Familia – Spain",
  "Watch the Monjuic Magic Fountain – Spain",
  "See the Rio Tinto River – Spain",
  "Run With the Bulls in Pamplona – Spain",
  "Climb to the Top of Sigiriya Rock – Sri Lanka",
  "Eat Fondue in Switzerland – Switzerland",
  "Hike the Matterhorn Trail – Matterhorn in Zermatt.",
  "Sit in the Outdoor Jacuzzi at Iglu-Dorf Hotel – Switzerland",
  "Ski the Swiss Alps – Switzerland",
  "Safari Through Serengeti – Tanzania",
  "Witness the Wildebeest Migration in Serengeti – Tanzania",
  "See the Tessellated Pavement – Tasmania",
  "Let Go of a Floating Lantern at Yi Peng Festival – Thailand",
  "Balloon Over Cappadocia’s Fairy Chimneys – Turkey",
  "Hear the Call to Prayer at the Blue Mosque – Turkey",
  "See the Whirling Dervishes – Turkey",
  "Soak in Pamukkale Hot Springs – Turkey",
  "Cross the Tunnel of Love – Ukraine",
  "Visit Stonehenge – United Kingdom",
  "Shop at the Floating Market – Vietnam",
  "Cruise through Ha Long Bay – Vietnam",
];

const Unesco = [
  "Visit The Iguazu National Park In Argentina",
  "Visit The Sydney Opera House In Australia",
  "Visit The The Great Barrier Reef In Australia",
  "Visit The Historic Center of Vienna In Austria",
  "Visit The Le Grand-Place in Brussels In Belgium",
  "Visit The Mostar In Bosnia & Herzegovina",
  "Visit The Carioca Landscape, Rio de Janeiro In Brazil",
  "Visit The Iguazu Falls In Brazil & Argentina",
  "Visit The Rila Monastery In Bulgaria",
  "Visit The Angkor In Cambodia",
  "Do the Edge Walk at CN Tower In Canada",
  "Visit The Landscapes of the Grand Pré In Canada",
  "Visit The Old Town of Lunenburg In Canada",
  "Visit The Easter Island In Chile",
  "Visit The The Forbidden City In China",
  "Visit The Plitvice Lakes In Croaita",
  "Visit The La Habana Vieja or Old Havana In Cuba",
  "Visit The Cesky Krumlov In Czech Republic",
  "Visit The Historic Centre of Prague In Czech Republic",
  "Visit The Kronburg Castle In Denmark",
  "Visit The Galapagos Islands In Ecuador",
  "Visit The City of Bath In England",
  "Visit The Historic Centre of Old Tallinn In Estonia",
  "Visit The Pyramids of Giza In Egypt",
  "Visit The Arles Roman and Romanesque Monuments In France",
  "Visit The Cathedral of Notre-Dame In France",
  "Visit The Historic Centre of Avignon In France",
  "Visit The Historic Centre of Lyon In France",
  "Visit The Palace and Gardens of Versailles In France",
  "Visit The Cologne Cathedral In Germany",
  "Visit The Old Town of Regensburg In Germany",
  "Visit The Upper Middle Rhine Valley In Germany",
  "Visit The Acropolis In Greece",
  "Visit The Archaeological Site of Delphi In Greece",
  "Visit The Meteora Monasteries In Greece",
  "Visit The Mount Athos In Greece",
  "Visit The Antigua In Guatemala",
  "Visit The Budapest In Hungary",
  "Visit The Ellora Caves In India",
  "Visit The Hill Forts of Rajasthan In India",
  "Visit The Jantar Mantar In India",
  "Visit The Keoladeo National Park In India",
  "Visit The Taj Mahal In India",
  "Visit The Cultural Landscape of Bali In Indonesia",
  "Visit The Borobudur Temple In Indonesia",
  "Visit The Prambanan Temple In Indonesia",
  "Visit The Taman Ayun Temple In Indonesia",
  "Visit The Brú na Bóinne In Ireland",
  "Visit The Skellig Michael In Ireland",
  "Visit The old City of Jerusalem In Israel",
  "Visit The Cinque Terre In Italy",
  "Visit The Historic Center of Florence In Italy",
  "Visit The Historic Center of San Gimignono In Italy",
  "Visit The Historic Center of Siena In Italy",
  "Visit The Piazza del Duomo in Pisa In Italy",
  "Visit The Venice and Its Lagoon In Italy",
  "Visit The Ancient Kyoto In Japan",
  "Visit The Mount Fuji In Japan",
  "Visit The Petra In Jordan",
  "Visit The Wadi Rum In Jordan",
  "Visit The City of Valletta In Malta",
  "Visit The Chichen-Itza In Mexico",
  "Visit The Historic centre of Mexico City and Xochimilco In Mexico",
  "Visit The Islands of Gulf of California In Mexico",
  "Visit The Protective Town of San Miguel In Mexico",
  "Visit The Medina of Marrakesh In Morocco",
  "Visit The Kinderdijk Windmills In Netherlands",
  "Visit The Giant’s Causeway and Causeway Coast In Norther Ireland",
  "Visit The Rock Islands Southern Lagoon In Palau",
  "Visit The City of Cusco In Peru",
  "Visit The Machu Picchu In Peru",
  "Visit The Historic Centre of Warsaw In Poland",
  "Visit The Cultural Landscape of Sintra In Portugal",
  "Visit The Historic Centre of Porto In Portugal",
  "Visit The St. Petersburg In Russia",
  "Visit The Old and New Towns of Edinburgh In Scotland",
  "Visit The Singapore Botanic Gardens In Singapore",
  "Visit The Lake Bled In Slovenia",
  "Visit The Historic Walled Town of Cuenca In Spain",
  "Visit The Works of Antoni Gaudi In Spain",
  "Visit The Sacred City of Kandy In Sri Lanka",
  "Visit The Sigiriya In Sri Lanka",
  "Visit The Old City of Bern In Switzerland",
  "Visit The Swiss Alps Jungfrau-Aletsch In Switzerland",
  "Visit The Ngorongoro Conservation Area In Tanzania",
  "Visit The Serengeti National Park In Tanzania",
  "Visit The Goreme National Park and the Rock Sites of Cappadocia In Turkey",
  "Visit The Historic Areas of Istanbul In Turkey",
  "Visit The Tower of London In United Kingdom",
  "Visit The Carlsbad Caverns National Park In United States",
  "Visit The Grand Canyon National Park In United States",
  "Visit The Mammoth Cave National Park In United States",
  "Visit The San Antonio Missions In United States",
  "Visit The Statue of Liberty In United States",
  "Visit The Yellowstone National Park In United States",
  "Visit The Yosemite National Park In United States",
  "Visit The Ha Long Bay In Vietnam",
  "Visit The Hoi An In Vietnam",
];

module.exports = {
  Data: {
    [Types.Adventure]: [...Adventure],
    [Types.Nature]: [...Nature],
    [Types.Creative]: [...Creative],
    [Types.People]: [...People],
    [Types.Entertainment]: [...Entertainment],
    [Types.Chef]: [...Chef],
    [Types.Food]: [...Food],
    [Types.Fun]: [...Fun],
    [Types.Growth]: [...Growth],
    [Types.Health]: [...Health],
    [Types.Transportation]: [...Transportation],
    [Types.Global]: [...Global],
    [Types.Travel]: [...Travel],
    [Types.Unesco]: [...Unesco],
  },
};
